### ISSUE TITLE
MVPレビュー

### ISSUE THREAD

**Issue by kerochelo** [naqprog/chengyu_test#103]
@naqprog 
MVPリリースお疲れ様でした！
下記にフィードバック内容をあげたのでご確認ください。

## UI/見た目
- アカウント登録のフォームの項目の順番を整えましょう。（一般的なサービスに従うのがいいですね）
- 成語4択テスト画面の下部に問題IDが出ているので消しておきましょう。
- 細かい文言をわかりやすく修正する（解答画面の「入力」=>「あなたが選んだ答え」など）
- どんなアプリか使い方ページ作ると良さそうです
- 全体的にUIを整えておく（bootstrapのテンプレートを参考にするといいので探してみてください）
- 次の問題解く時の問題種別が意味から成語を選択する問題に固定になっちゃうので、設定に合わせるように修正しましょう

## コード/技術
- node_moduleもgit管理下に入ってるのでgitignoreしておきましょう
- bookmarks_controllerのindexアクションのeachはmapでいいかもです
- exercises_controllerの処理はresourcesベースにしてCRUD中心でリファクタを進めてみてください
- responses_controllerのindexアクションはprivateメソッド切り出しとmodelのメソッド切り出してあげましょう
- responses_controllerのdailyアクションは1つのcontrollerとして切り出しindexのアクションで対応してみてください

全体的に細かい部分まで考慮されており、UI面を整えればかなりアプリとして完成度が高いかなと思います！
上記内容をissueなどで落とし込んでもらいましたら、こちらのissueはcloseしていただいて構いません。

以上よろしくお願いいたします。

**Comment by naqprog** [comment]
ありがとうございます。
新しくissueとして整理・作成しましたので本issueはcloseいたします。
