### ISSUE TITLE
MVPリリースに向けてReadme改稿

### ISSUE THREAD

**Issue by naqprog** [naqprog/chengyu_test#72]
MVP開発中に、本Releaseで実装するはずで前倒された、あるいは全く新規実装をした、
システムやモジュールが多数あるため、MVPリリース・講師レビューに向けて改稿を行う

**Comment by naqprog** [comment]
下記のように修正を行いました。ご確認をお願いいたします。
https://github.com/naqprog/chengyu_test/blob/main/README.md

【当初よりMVPに追加した内容】

* 当初権限については本リリースでの実装予定でしたがgem CanCanCanも実装しました
　(deviseの実装中CanCanCanを平行実装した方がスムーズだと考えられた為)

* ウェルカムメール、パスワードを忘れた際のメールを配信する機能を実装しました
　(Production環境ではGmailを利用して配信
　　Development環境ではmailcatcherをdocker上に用意して確認)

* 出題に関しては本リリースでの実装予定でした「成語から意味を答える」モードも実装を行いました

* 出題ルールに関しても下記ができるように実装しました
  * 過去間違った問題から出題
  * 正答率が低い問題から出題
  * お気に入りに入れた問題からだけ出題

* UserとQuestionモデルの多対多テーブルBookmarkに複数フラグを持たせ、「お気に入り」だけでなく「既知」という状態も管理できるようにしました
　この既知フラグが立っている問題は(すでに覚えてしまっているので)出題しないようになっています

* 単独ページとして下記を実装しました
  * チュートリアル(使い方)ページ
  * プライバシーポリシー

【MVPにおいて変更した点】

* 実装の面から、gem ActiveAdminではなくRailsAdminを採用しました

* オートコンプリート機能に関しては一旦HTML5の機能にて実装しました
　本サービスまでにstimulus-autocompleteを利用して実装し直す予定です
　https://github.com/afcapel/stimulus-autocomplete

* 遷移を検討した結果、出題ルールに関しては問題の初回時に選ばせるのではなく、設定ページで選ばせるように変更しました
　(初回はみんな「全ての問題から出題する」人がほとんどだから)

【当初より本サービスに追加した内容】

* テスト機能をアップデートし、成語を答えさせる問題にヒント機能を付加
　(問題が難しすぎるため)

* 出題ルールにカスタマイズ機能を実装
　(例えば「過去30日の間に間違った問題から出題」などのようなことができるようにする)

**Comment by Tsuchiya2** [comment]
LGTMです
